.pragma library

var eventTags = {
    open: "shader_open",
    close: "shader_close",
    move: "shader_move",
    resize: "shader_resize",
    workspace: "shader_workspace",
    fullscreenEnter: "shader_fullscreen_enter",
    fullscreenExit: "shader_fullscreen_exit",
    float: "shader_float",
    tile: "shader_tile",
    focus: "shader_focus",
    unfocus: "shader_unfocus",
    urgent: "shader_urgent"
}

function luaString(value) {
    return "\"" + String(value).replace(/\\/g, "\\\\").replace(/\"/g, "\\\"") + "\""
}

function exactClass(value) {
    var escaped = String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    return "^(" + escaped + ")$"
}

function safeName(value) {
    return String(value).toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "application"
}

function rule(name, classPattern, tag) {
    return [
        "hl.window_rule({",
        "    name = " + luaString(name) + ",",
        "    match = { class = " + luaString(classPattern) + " },",
        "    tag = " + luaString("+" + tag) + ",",
        "})"
    ].join("\n")
}

function shaderSpec(effectId, path) {
    return effectId === "simple-wobble" ? path + "@0.35" : path
}

function generate(enabled, events, paths, excludedClasses, passthroughPath) {
    var lines = [
        "-- Generated by OmaDecor. Manual edits will be overwritten.",
        "-- This file owns only rules named omadecor-effects-*.",
        ""
    ]
    if (!enabled) {
        lines.push("-- Effects are disabled or safely suspended.", "")
        return lines.join("\n")
    }

    var configured = []
    for (var eventName in eventTags) {
        var effectId = String(events[eventName] || "none")
        var path = String(paths[effectId] || "")
        if (effectId === "none" || path === "") continue
        var tagName = eventTags[eventName]
        configured.push({ eventName: eventName, tagName: tagName })
        lines.push(rule(
            "omadecor-effects-" + eventName.toLowerCase() + "-default",
            ".*",
            tagName + "_default:" + shaderSpec(effectId, path)
        ), "")
    }

    for (var classIndex = 0; classIndex < excludedClasses.length; classIndex++) {
        var appClass = String(excludedClasses[classIndex] || "")
        if (!/^[A-Za-z0-9._:+-]{1,128}$/.test(appClass)) continue
        for (var tagIndex = 0; tagIndex < configured.length; tagIndex++) {
            var item = configured[tagIndex]
            lines.push(rule(
                "omadecor-effects-exclude-" + safeName(appClass) + "-" + item.eventName.toLowerCase(),
                exactClass(appClass),
                item.tagName + ":" + passthroughPath
            ), "")
        }
    }
    return lines.join("\n")
}
