.pragma library

var eventTags = {
    open: "shader_open",
    close: "shader_close",
    move: "shader_move",
    resize: "shader_resize",
    workspace: "shader_workspace",
    fullscreenEnter: "shader_fullscreen_enter",
    fullscreenExit: "shader_fullscreen_exit",
    float: "shader_float",
    tile: "shader_tile",
    focus: "shader_focus",
    unfocus: "shader_unfocus",
    urgent: "shader_urgent"
}

function luaString(value) {
    return "\"" + String(value).replace(/\\/g, "\\\\").replace(/\"/g, "\\\"") + "\""
}

function exactClass(value) {
    var escaped = String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    return "^(" + escaped + ")$"
}

function safeName(value) {
    return String(value).toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "application"
}

function rule(name, classPattern, tag) {
    return [
        "hl.window_rule({",
        "    name = " + luaString(name) + ",",
        "    match = { class = " + luaString(classPattern) + " },",
        "    tag = " + luaString(tag.charAt(0) === "-" ? tag : "+" + tag) + ",",
        "})"
    ].join("\n")
}

function shaderSpec(effectId, path, eventName, timings) {
    if (effectId === "none") return path
    var seconds = Number((timings || {})[eventName])
    if (!isFinite(seconds)) return path
    seconds = Math.max(0, Math.min(5, seconds))
    return path + "@" + String(Math.round(seconds * 100) / 100)
}

function previousOwnedTags(previousText) {
    var tags = []
    var seen = ({})
    var ownedRule = false
    var classPattern = ""
    var lines = String(previousText || "").split("\n")
    for (var index = 0; index < lines.length; index++) {
        var line = lines[index].trim()
        if (line === "hl.window_rule({") {
            ownedRule = false
            classPattern = ""
        }
        var name = line.match(/^name = "(omadecor-effects-[^"]+)",$/)
        if (name) ownedRule = true
        var classLine = line.match(/^match = \{ class = ("(?:\\.|[^"\\])*") \},$/)
        if (ownedRule && classLine) {
            try { classPattern = JSON.parse(classLine[1]) }
            catch (error) { classPattern = "" }
        }
        if (ownedRule && classPattern !== "" && line.indexOf("tag = ") === 0) {
            var encoded = line.slice("tag = ".length).replace(/,$/, "")
            var tag
            try { tag = JSON.parse(encoded) }
            catch (error) { continue }
            if (typeof tag !== "string" || !/^\+shader_[a-z_]+:/.test(tag)
                    || seen[classPattern + "\n" + tag]) continue
            seen[classPattern + "\n" + tag] = true
            tags.push({ tag: tag, classPattern: classPattern })
        }
        if (line === "})") ownedRule = false
    }
    return tags
}

function legacyOwnedTags(clientsText, managedRoots) {
    var clients
    try { clients = JSON.parse(String(clientsText || "")) }
    catch (error) { return [] }
    if (!Array.isArray(clients)) return []
    var roots = Array.isArray(managedRoots) ? managedRoots : []
    var seen = ({})
    var result = []
    var prefix = /^shader_(?:open|close|move|resize|workspace|fullscreen_enter|fullscreen_exit|float|tile|focus|unfocus|urgent)_default:/
    for (var index = 0; index < clients.length; index++) {
        var tags = Array.isArray(clients[index].tags) ? clients[index].tags : []
        for (var tagIndex = 0; tagIndex < tags.length; tagIndex++) {
            var value = String(tags[tagIndex] || "")
            if (!value.endsWith("*") || !prefix.test(value)) continue
            value = value.slice(0, -1)
            var shaderPath = value.slice(value.indexOf(":") + 1)
            if (shaderPath.indexOf("/../") !== -1 || shaderPath.indexOf("/./") !== -1)
                continue
            var managed = false
            for (var rootIndex = 0; rootIndex < roots.length; rootIndex++) {
                var root = String(roots[rootIndex] || "")
                if (root !== "" && shaderPath.indexOf(root) === 0) managed = true
            }
            if (managed && !seen[value]) {
                seen[value] = true
                result.push({ tag: "+" + value, classPattern: ".*" })
            }
        }
    }
    return result
}

function generate(enabled, events, timings, paths, applications, passthroughPath,
        previousText, clientsText, managedRoots) {
    var lines = [
        "-- Generated by OmaDecor. Manual edits will be overwritten.",
        "-- This file owns only rules named omadecor-effects-*.",
        ""
    ]
    if (!enabled) {
        lines.push("-- Effects are disabled or safely suspended.", "")
    }

    var previousTags = previousOwnedTags(previousText)
        .concat(legacyOwnedTags(clientsText, managedRoots))
    var seenTags = ({})
    var cleanupCount = 0
    for (var cleanupIndex = 0; cleanupIndex < previousTags.length; cleanupIndex++) {
        var previous = previousTags[cleanupIndex]
        var key = previous.classPattern + "\n" + previous.tag
        if (seenTags[key]) continue
        seenTags[key] = true
        cleanupCount++
        lines.push(rule(
            "omadecor-effects-cleanup-" + String(cleanupCount),
            previous.classPattern, "-" + previous.tag.slice(1)
        ), "")
    }

    if (!enabled) {
        return lines.join("\n")
    }

    var configured = []
    for (var eventName in eventTags) {
        var effectId = String(events[eventName] || "none")
        var path = String(paths[effectId] || "")
        if (effectId === "none" || path === "") continue
        var tagName = eventTags[eventName]
        configured.push({ eventName: eventName, tagName: tagName })
        lines.push(rule(
            "omadecor-effects-" + eventName.toLowerCase() + "-default",
            ".*",
            tagName + "_default:" + shaderSpec(effectId, path, eventName, timings)
        ), "")
    }

    for (var classIndex = 0; classIndex < applications.length; classIndex++) {
        var application = applications[classIndex] || {}
        var appClass = String(application.appClass || "")
        if (!/^[A-Za-z0-9._:+-]{1,128}$/.test(appClass)) continue

        if (application.disableEffects === true) {
            for (var tagIndex = 0; tagIndex < configured.length; tagIndex++) {
                var excludedItem = configured[tagIndex]
                lines.push(rule(
                    "omadecor-effects-exclude-" + safeName(appClass) + "-" + excludedItem.eventName.toLowerCase(),
                    exactClass(appClass),
                    excludedItem.tagName + ":" + passthroughPath
                ), "")
            }
            continue
        }

        var overrides = application.effectOverrides && typeof application.effectOverrides === "object"
            ? application.effectOverrides : {}
        for (var overrideEvent in overrides) {
            var overrideTag = eventTags[overrideEvent]
            if (!overrideTag) continue
            var overrideId = String(overrides[overrideEvent] || "global")
            if (overrideId === "global") continue
            var overridePath = overrideId === "none" ? passthroughPath : String(paths[overrideId] || "")
            if (overridePath === "") continue
            lines.push(rule(
                "omadecor-effects-override-" + safeName(appClass) + "-" + overrideEvent.toLowerCase(),
                exactClass(appClass),
                overrideTag + ":" + shaderSpec(overrideId, overridePath, overrideEvent, timings)
            ), "")
        }
    }
    return lines.join("\n")
}
